### ISSUE TITLE
variable with file path not working

### ISSUE THREAD

**Issue by weirdcrap** [weirdcrap/magnet2torrent#3]
To save the user from having to change the file path in multiple places in the script I wanted to define a simple variable in the first line like this:

`RTORRENTWATCH=~/pathtodir/`

Testing the script with this setup gets me this:
```
find: ‘~/movie-watch/*.torrent’: No such file or directory
./magnet2torrent: line 47: cd: ~/movie-watch/: No such file or directory
cat: '~/movie-watch/*.magnet': No such file or directory

```
so the variable appears to be working as I see the proper paths but find, cat, and cd don't like this setup as I keep getting not found errors.

I am no shell script expert by any means, so if someone comes across this before I get around to fixing it and knows what's wrong put in a pull request.

**Comment by phatpaul** [comment]
fixed in PR #4
